### ISSUE TITLE
Look for folder in case-insensitive manner

### ISSUE THREAD

**Issue by krasnoukhov** [cowens/tornexto#2]
See Chris Hillery comment here: http://theoldreader.uservoice.com/forums/187017-feature-requests/suggestions/3743410-bookmarklet-to-go-to-next-item-in-a-folder

**Comment by cowens** [comment]
Interesting, this should be fixed when I implement the list of folders.
Beyond that I think it would have to be fixed at the API level since I am
passing the name of the folder without any changes to the API.

**Comment by cowens** [comment]
Hmm, a more careful reading of the message seems to say that the folder name should always be all lowercase.  Is that correct?

**Comment by krasnoukhov** [comment]
No, users are able to set folder title using both lower and uppercase letters. But I think using your new shiny "home" page it's necessary, so i'm closing this. Just add home link to README :+1:
