### ISSUE TITLE
No Longer Functional Due to Go 1.9

### ISSUE THREAD

**Issue by Ruduen** [cowens/tornexto#5]
This currently does not function, due to Google's feature depreciation of Go 1.9. It should be possible to start using the Go 1.11 standard runtime instead (https://goo.gl/aESk5L).

**Comment by cowens** [comment]
I have stopped using The Old Reader in favor of my own homegrown feed reader that is being crafted to exactly what I want (rather than paying them $20 a year to ignore me).  You are welcome to fork this project and get it up and running on Google Cloud if you want.
